config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :friendships
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:new, :create, :show, :index]

  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships, only: [:new, :index, :show]
  get 'notifications/new'
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def new    
    @incoming_friend_requests = current_user.incoming_friend_requests
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/new.html.erb
<h1>Notifications</h1>
<div class="row">
  <% @incoming_friend_requests.each do |request| %>
    <div class="col-sm-5 col-sm-offset-2">
      <h3><%= request.user.first_name %></h3>
    </div>
    <div class="col-sm-5">
      <div class="row">
        <% if request.friend %>
          <div class="col-sm-2">
            <%= button_to "Confirm", friendship_path(request.id), :method => :patch,  class: 'btn btn-success' %>
          </div>
          <div class="col-sm-2">
            <%= button_to "Reject", friendship_path(request.id), method: :delete, class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <br>
</div>