config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :friendships
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:new, :create, :show, :index]

  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships, only: [:new, :index, :show]
  get 'notifications/new'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook] 


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy  
  has_many :friendships, dependent: :destroy

  has_many :friends, through: :friendships, source: :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  scope :all_except, ->(user) { where.not(id: user) }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name, user.last_name = auth.info.name.split(" ")[0] 
      user.gender = "gender"
      user.birthday = Time.now
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def sent_friend_requests
    Friendship.where(['user_id = ? and confirmed = ?', id, false])
  end

  def incoming_friend_requests
    Friendship.where(['friend_id = ? and confirmed = ?', id, false])
  end

  
  def feed
    Post.where('user_id in (SELECT friend_id FROM friendships WHERE
      user_id = :user) or user_id = :user', user: self.id).order(created_at: :desc)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   #before_action :configure_sign_in_params, only: [:create]

   def new
     super
   end

   def create
     super
   end

   def destroy
     super
   end

   protected

   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.all_except(current_user)        
  end

  def show
    @user = current_user
    @posts = @user.posts
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size:100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "//www.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <div class="row">
    <div class="col-sm-5 col-sm-offset-2">
      <h3 class="display-4"><%= user.first_name%></h3>
    </div>
    <div class="col-sm-5">
      <% if current_user.friendships.exists?(friend: user, confirmed: false) %>
        <%= button_tag "Friend Request Sent", disabled:true, class: 'btn btn-danger' %>
      <% elsif current_user.friendships.exists?(friend: user, confirmed: true) %>
        <%= button_tag "You Both are Friends", disabled:true, class: 'btn-secondary active' %>
      <% else %>
        <%= button_to "Add Friend", friendships_path(friend_id: user.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
<% end %>
<br>

app/views/users/show.html.erb
<div class="row">
  <div class="col-12 text-center">
    <h3>Profile</h3>
    <hr>
    <h4><%= gravatar_for @user %></h4>
    <h4>Name: <%= @user.first_name %></h4>
    <h4>Email: <%= @user.email %></h4>
  </div>
</div>