config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :friendships
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:new, :create, :show, :index]

  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships, only: [:new, :index, :show]
  get 'notifications/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_presence_of :body
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_destroy :destroy_inverse_relationship
  
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  validates_presence_of :user_id, :friend_id
  validates :user_id, uniqueness: { case_sensitive: false, scope: :friend_id }

  def confirm
    update(confirmed: true)
    create_inverse_relationship
  end

  private

  def create_inverse_relationship
    friend.friendships.create(friend: user, confirmed: true)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :content, length: {maximum: 140}, presence: true
  validates :title, length: {minimum:10}, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook] 


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy  
  has_many :friendships, dependent: :destroy

  has_many :friends, through: :friendships, source: :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  scope :all_except, ->(user) { where.not(id: user) }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name, user.last_name = auth.info.name.split(" ")[0] 
      user.gender = "gender"
      user.birthday = Time.now
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def sent_friend_requests
    Friendship.where(['user_id = ? and confirmed = ?', id, false])
  end

  def incoming_friend_requests
    Friendship.where(['friend_id = ? and confirmed = ?', id, false])
  end

  
  def feed
    Post.where('user_id in (SELECT friend_id FROM friendships WHERE
      user_id = :user) or user_id = :user', user: self.id).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @comment = Comment.new()
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :birthday, :gender) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post
    if @comment.save
      flash[:success] = 'Your comment has been created'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  def index
    @friendships = current_user.friendships.where(confirmed: true)
  end


  def create
    @new_friendship = Friendship
      .new(user: current_user, friend_id: params[:friend_id])
    if @new_friendship.save!
      flash[:notice] = 'Confirmation sent'
    else
      flash[:notice] = 'Cannot send twice'
    end
    redirect_to users_path
  end

  def update
    @confirm_request = current_user.incoming_friend_requests.find(params[:id])
    @confirm_request.confirm
    flash[:notice] = 'You are now Friends'
    redirect_to friendships_path
  end

  def destroy
    @friendship = Friendship
      .where(friend: current_user)
      .or(Friendship.where(user: current_user))
      .find(params[:id])
    @friendship.destroy
    flash[:notice] = 'Removed friendship.'
    redirect_to friendships_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  
  def create
    if already_liked?
      flash.now[:notice] = "You already liked this post"      
    else
      @post.likes.create(user_id:current_user.id)
    end
    redirect_back fallback_location: post_path(@post)
  end

  def destroy
    if !(already_liked?)
      flash.now[:notice] = "cannot unlike!"
    else
      find_like.destroy
    end
    redirect_back fallback_location: post_path(@post)
  end

  private 
    def find_post
      @post = Post.find(params[:post_id])
    end

    def find_like
      @like = @post.likes.find(params[:id])
    end

    def already_liked?
      Like.where(user_id:current_user.id, post_id:params[:post_id]).exists?
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def new    
    @incoming_friend_requests = current_user.incoming_friend_requests
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @users = User.all
    # # @posts = current_user.posts.all.order(created_at: :desc)
    # @posts = current_user.timeline
    if !(user = params[:user_id]&.to_i)
      @posts = current_user.feed
    elsif (user == current_user.id) ||
      (current_user.friends.include?(User.find_by_id(user)))
      @posts = Post.where(user_id: user)
    else
      flash.now[:warning] = "You can only see your and your friends' posts."
      @posts = current_user.feed
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Posts created!"
      redirect_to authenticated_root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def comment_params
    params.require(:comment).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.all_except(current_user)        
  end

  def show
    @user = current_user
    @posts = @user.posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size:100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "//www.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "odinfacebook", new_user_registration_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="lead"><%= link_to current_user.first_name, user_path(:id) %></li>
          <li><%= link_to "Home", posts_path %></li>
          <li><%= link_to "Notifications", notifications_new_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Friends", friendships_path(:id) %></li>
          <li><%= link_to "Post", new_post_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Settings', edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= render 'layouts/rails_default' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_comments.html.erb
<% @comments.each do %>
<% end %>

app/views/shared/_post.html.erb
<% @posts.each do |post| %>
<strong>Title: </strong><%= post.title %><br>
<strong>Content: </strong><%= post.content %>
<% end %>

app/views/shared/_post_comments.html.erb
<% @post.comments.each do |comment| %>
  <%= comment.title %>
  <%= comment.body %>
<% end %>

app/views/shared/_posts.html.erb
  <%= render 'shared/user_posts' %>

app/views/shared/_user.html.erb
<% @users.each do |user| %>
  <%= user.first_name %><br/>
<% end %>

app/views/shared/_user_posts.html.erb
<% @posts.each do |post| %>
  <%# <% if current_user == post.user %>
    <%= link_to post.user.first_name, user_path(post.user) %><br>
    <strong>Title: </strong><%= post.title %><br>
    <strong>Content: </strong><%= post.content %>
      <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like', post_likes_path(post), method: :post %>
    <% end %>
    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <strong>Comments(<%= post.comments.count %>)</strong><br>
    <% post.comments.each do |comment| %>
      <%= comment.body %><br>
    <% end %>
    <%= link_to 'New Comment', new_post_comment_path(post) %>
    <hr>
    <%# <% end %>
<% end %>

app/views/shared/_users.html.erb
<% @users.each do |user| %>
  <%= user.first_name %>
  <%= link_to 'Add a friend', "#", class: "btn btn-default" %>
  <br>
<% end %>